--회원 정보를 저장할 테이블 (MEMBER)
CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY, -- 회원번호 
    USERID VARCHAR2(20) NOT NULL UNIQUE,--회원아이디
    -- 회원 비밀번호 
    USERPW VARCHAR2(20) NOT NULL, -- 회원 비밀번호 
    USERNMME VARCHAR2(20) NOT NULL,-- 이름 
    GENDER CHAR(1) CHECK(GENDER IN('M','F')),
    AGE NUMBER , -- 나이
    EMAIL VARCHAR2(30),
    ADDRESS VARCHAR2(100),-- 주소 
    PHONE VARCHAR2(13),
    HOBBY VARCHAR2(50),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL --가입일 
);

DROP SEQUENCE SEQ_USERNO;

CREATE SEQUENCE SEQ_USERNO
NOCACHE;
-- 테이블 스페이스 설정 
ALTER USER C##JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

INSERT INTO MEMBER
VALUES(SEQ_USERNO.NEXTVAL, 'ADMIN', '1234','관리자','M',20,'admin@kh.or.kr', '서울', '010-1010-0101',NULL,'2020-07-30');

INSERT INTO MEMBER
VALUES(SEQ_USERNO.NEXTVAL, 'whdrns456', '1234','최종군','M',20,'whdrns456@kh.or.kr', '서울 금천구', '010-2725-0780',NULL, DEFAULT);

COMMIT;






